apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudeploy1
  name: ashudeploy1 # name of deployment 
  namespace: ashuspace  # namespace info 
spec:
  replicas: 1 # same as RC -- no of pod 
  selector:
    matchLabels:
      app: ashudeploy1
  strategy: {}
  template: # template same as RC 
    metadata:
      creationTimestamp: null
      labels: # label of PODs 
        app: ashudeploy1
    spec:
      containers:
      - image: dockerashu/oraclweb:may62021v1 # docker image 
        name: oraclweb # name of container 
        env:
        - name: x
          value: app1 
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: s1
  name: s1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: ashudeploy1
  type: NodePort
status:
  loadBalancer: {}
